config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  resources :notes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])

    if @note.update(note_params)
      redirect_to notes_path
    else
      render :edit
    end
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to notes_path
    else
      render :new
    end
  end

  def destroy 
    Note.find(params[:id]).destroy 
    redirect_to notes_path 
  end

  private

  def note_params
    params.require(:note).permit(:title, :body)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/static_pages_controller_helper.rb
module StaticPagesControllerHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'home', static_pages_home_path %>
<%= link_to 'notes', notes_path %>
</br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostItNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h1>Edit</h1>
<%= form_for @note do |f|%>
  <%= f.label :title%>
  <%= f.text_field :title%>

  <%= f.label :body%>
  <%= f.text_area :body%>

  <%= f.submit%>
<% end %>

app/views/notes/index.html.erb
<h1>Post It Notes</h1>
<% @notes.each do |note| %>
  <%= note.title %>
  <ul>
 <li> <%= link_to 'Show Note', note_path(note.id) %></li>
  <li><%= link_to 'Edit Note', edit_note_path(note.id) %></li>
 <li> <%= link_to 'Delete Note', note, method: :delete %></li>
  </ul>
<% end %>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<%= form_for @note do |f| %>
  <%= f.label :title%>
  <%= f.text_field :title%>

  <%= f.label :body%>
  <%= f.text_area :body%>

  <%= f.submit%>
<% end %>

app/views/notes/show.html.erb
<b><%= @note.title %></b>
</br>

<%= @note.body%>
</br>

<%= link_to 'Back', notes_path%>

app/views/static_pages/home.html.erb
<h1>Home Page</h1>
<p>Welcome to Dylan's Sticky Note Page</p>